### Add a new organisation
POST https://localhost:7212/api/Organisations
Content-Type: application/json

{
  "orgName": "New Organisation",
  "orgDescription": "This is a test organisation.",
  "foundedDate": "2024-12-28",
  "contactEmail": "test@organisation.com"
}

###add event
POST https://localhost:7212/Event/Add
Content-Type: application/json

{
"eventName": "Nieuw Event",
"eventDate": "2024-12-30T19:00:00",
"ticketPrice": 25.00,
"eventDescription": "Beschrijving van het evenement.",
"category": 1
}

### add ticket
POST https://localhost:7212/api/Tickets
Content-Type: application/json

{
  "eventId": 4,
  "visitorId": 1,
  "paymentMethode": "test"
}

###get event details
GET https://localhost:7212/Event/Details/3
Content-Type: application/json


### Add a new organisation without being logged in (should fail)
POST https://localhost:7212/api/Organisations
Content-Type: application/json

{
  "orgName": "Unauthenticated Organisation",
  "orgDescription": "This organisation should fail to be added.",
  "foundedDate": "2024-12-29",
  "contactEmail": "unauth@organisation.com"
}


### Add a new organisation as a logged-in user (should succeed)
POST https://localhost:7212/api/Organisations
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8J4O2G8AWJdIkQdD96CjqsJHsNw5wI3JWFCmU2Wv7_q7sIyRNAJ3FDw3DmBqrTlz6G1GfowMQLMf279e0a_Ej2X6BpWIYoyzEOjSw0YK5DAB4BDx59DyxD7mZJBkAUzflfKpGulc95hEo4U-wmsbV4XUNXGvogYG747RRoKprX7RYd2L4kNVIGqXZ4LmLeRvPYmJjO-xTwjK9IuaUqo1B1qvJK0N2PUiq9uA30HRvzdBHJStoakOfWmzs1fiB3MvtM7OgQKIqWX5bp1ZPBOjiGVnJuLP2YutZLNvMHxfw7O5Tfjmn0y0rehpow7VV6bk3RQHbqTbvEY9BiWS3uVY1I3E954IgbJdRFqy4OgJBjtrhT-6hJKKsQ4hMlyx29AOFhvhyxfOa6_xahanyEc1CLk-vVdO49ZTaWrijP_beVJ7dsl2vBOx72TmI4sG8vGChKZhiKiKJ2Xx2F7EXNPxuWjcBq1yxlYlBIZSjfhpjb6FS8HrLecvfihOmOs1Oyp_asB3mtCwflw895YHoQA3cN0BnR026Jji2AJFTQsmgE_YLwHTlnlxV5V7xJicERVGgLAMLEK57SPhRlI8Q00MAM1BSDmEe-xR9bC8MRs03KvedevJhgbFboTxXtekkGvYpgKpkYrKxUf3p5prCXVB6ccSt52jfNeiq720NSAoPKQLXCF-m1G9fcELT67mH0CwOLPB_zVBPU5R31nYvRHizEFcHQGfi26lq-X8XxEzHTYr8-epNjdzqJmSH8dyFUVtYy7drOh240JSt-1WIzsK6tluddN50YdZO7Ivem6OMhpu5Q-Jr9UauhLMF1Yd3J32wg

{
  "orgName": "Authenticated Organisation",
  "orgDescription": "This organisation should be added successfully.",
  "foundedDate": "2024-12-29",
  "contactEmail": "auth@organisation.com"
}
